/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemasOperativos2;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanr
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private SistemaArchivos sistema;
    private DefaultTableModel modeloTabla;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        // --- PASO 2: AÑADE ESTA LÍNEA AQUÍ ---
        cargarSistemaArchivos();
        // --- FIN DE PASO 2 ---
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        arbolVisual = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaArchivos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(arbolVisual);

        tablaArchivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaArchivos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }
    
    /**
     * Inicia el Sistema de Archivos y carga los datos iniciales en el JTree.
     */
    private void cargarSistemaArchivos() {
        // 1. Crear nuestro "cerebro"
        // NOTA: Haremos 'sistema' una variable de la clase para usarla después
        
        this.sistema = new SistemaArchivos(); // Ya no tiene "SistemaArchivos" al inicio
        
        // --- (OPCIONAL) Añadir datos de prueba ---
        sistema.crearDirectorio("home", sistema.getRaiz());
        Directorio home = (Directorio) sistema.getRaiz().buscarHijo("home");
        sistema.crearArchivo("documento.txt", 3, home);
        sistema.crearArchivo("README.md", 1, sistema.getRaiz());
        // --- Fin datos de prueba ---
        
        // 2. Traducir nuestro Directorio (modelo) a un JTree (vista)
        DefaultMutableTreeNode nodoRaizVisual = crearNodosVisuales(sistema.getRaiz());
        
        // 3. Establecer este nuevo árbol en nuestro JTree
        // El DefaultTreeModel es el "administrador" del JTree
        this.arbolVisual.setModel(new DefaultTreeModel(nodoRaizVisual));
        
        configurarTablaArchivos(); // Prepara las columnas
        poblarTablaArchivos(this.sistema.getRaiz()); // Llena las filas
    }
    
    /**
     * Función RECURSIVA que "traduce" nuestra estructura de Directorio
     * a la estructura visual que el JTree entiende.
     * @param dirActual El Directorio (nuestro modelo) a traducir.
     * @return Un DefaultMutableTreeNode (el nodo visual) con todos sus hijos.
     */
    private DefaultMutableTreeNode crearNodosVisuales(Directorio dirActual) {
        
        // 1. Crear el nodo visual para ESTE directorio
        DefaultMutableTreeNode nodoVisual = new DefaultMutableTreeNode(dirActual.getNombre());

        // 2. Obtener la lista de hijos (nuestra ListaEnlazada)
        ListaEnlazada hijos = dirActual.getHijos();
        if (hijos.estaVacia()) {
            return nodoVisual; // Es un directorio vacío, terminamos.
        }

        // 3. Recorrer nuestra lista de hijos
        Nodo nodoHijoActual = hijos.getNodoCabeza();
        while (nodoHijoActual != null) {
            
            Object datoHijo = nodoHijoActual.getDato();
            
            if (datoHijo instanceof Directorio) {
                // Si el hijo es un Directorio... ¡RECURSIÓN!
                nodoVisual.add(crearNodosVisuales((Directorio) datoHijo));
                
            } else if (datoHijo instanceof Archivo) {
                // Si es un Archivo, es una "hoja"
                Archivo archivo = (Archivo) datoHijo;
                String nombreArchivo = archivo.getNombre() + " (" + archivo.getTamanoEnBloques() + "b)";
                DefaultMutableTreeNode nodoHoja = new DefaultMutableTreeNode(nombreArchivo);
                nodoVisual.add(nodoHoja);
            }
            
            // Avanzamos en nuestra ListaEnlazada
            nodoHijoActual = nodoHijoActual.getSiguiente();
        }
        
        return nodoVisual;
    }
    
    /**
     * Configura las columnas para nuestra tabla de archivos (JTable).
     */
    private void configurarTablaArchivos() {
        // 1. Crear el modelo
        this.modeloTabla = new DefaultTableModel();
        
        // 2. Añadir las columnas según el PDF 
        this.modeloTabla.addColumn("Nombre Archivo");
        this.modeloTabla.addColumn("Cant. Bloques");
        this.modeloTabla.addColumn("Bloque Inicial");
        
        // 3. Asignar el modelo a nuestra tabla visual
        this.tablaArchivos.setModel(this.modeloTabla);
    }

    /**
     * Función RECURSIVA que recorre el árbol de directorios
     * y añade cada ARCHIVO que encuentra a la tabla.
     * @param dirActual El directorio a escanear.
     */
    private void poblarTablaArchivos(Directorio dirActual) {
        // 1. Obtener la lista de hijos
        ListaEnlazada hijos = dirActual.getHijos();
        if (hijos.estaVacia()) {
            return; // No hay nada que hacer
        }

        // 2. Recorrer la lista de hijos
        Nodo nodoHijoActual = hijos.getNodoCabeza();
        while (nodoHijoActual != null) {
            
            Object datoHijo = nodoHijoActual.getDato();
            
            if (datoHijo instanceof Directorio) {
                // Si es un directorio, RECURSIÓN: escanearlo por dentro
                poblarTablaArchivos((Directorio) datoHijo);
                
            } else if (datoHijo instanceof Archivo) {
                // Si es un Archivo, ¡lo añadimos a la tabla!
                Archivo archivo = (Archivo) datoHijo;
                
                // Creamos una fila de datos
                Object[] fila = new Object[3];
                fila[0] = archivo.getNombre();
                fila[1] = archivo.getTamanoEnBloques();
                fila[2] = archivo.getPrimerBloque();
                
                // Añadimos la fila al modelo
                this.modeloTabla.addRow(fila);
            }
            
            // Avanzamos en nuestra ListaEnlazada
            nodoHijoActual = nodoHijoActual.getSiguiente();
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbolVisual;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaArchivos;
    // End of variables declaration//GEN-END:variables
}
