/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import CoreV2.Cola;
import CoreV2.Nodo;
import CoreV2.Petition;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
/**
 *
 * @author verol
 */
public class PanelColaPeticiones extends javax.swing.JPanel {
private JPanel contenedorItems; 

    public PanelColaPeticiones() {
        initComponents();
        
        configurarPanel();
    }

    private void configurarPanel() {
        this.setLayout(new java.awt.BorderLayout());
        

        contenedorItems = new JPanel();
        contenedorItems.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        contenedorItems.setBackground(Color.WHITE);

        JScrollPane scroll = new JScrollPane(contenedorItems);
        scroll.setBorder(null); 
        scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        
        this.add(scroll, java.awt.BorderLayout.CENTER);
    }

    
    public void actualizarCola(Cola colaPeticiones) {
        contenedorItems.removeAll(); 

        if (colaPeticiones != null && !colaPeticiones.isEmpty()) {
            
            Nodo actual = colaPeticiones.getFrente();

            while (actual != null) {
                Petition p = actual.getPeticion();
                if (p != null) {
                    JPanel tarjeta = crearTarjetaPeticion(p);
                    contenedorItems.add(tarjeta);
                }
                actual = actual.getSiguiente();
            }
        }
        
        contenedorItems.revalidate();
        contenedorItems.repaint();
    }

    private JPanel crearTarjetaPeticion(Petition p) {
        JPanel panel = new JPanel();
        
        panel.setLayout(new GridLayout(3, 1)); 
        panel.setPreferredSize(new Dimension(100, 60)); 
        panel.setBackground(new Color(235,249,255)); 
        panel.setBorder(BorderFactory.createLineBorder(new Color(144,183,221), 1)); 

        JLabel lblTitulo = new JLabel("Petición " + p.getId(), SwingConstants.CENTER);
        lblTitulo.setFont(new Font("SansSerif", Font.BOLD, 11));
        lblTitulo.setForeground(Color.BLACK);
        
        String nombre = p.getFileName();
        if(nombre.length() > 10) nombre = nombre.substring(0, 12) + "..";
        
        JLabel lblArchivo = new JLabel(nombre, SwingConstants.CENTER);
        lblArchivo.setFont(new Font("SansSerif", Font.PLAIN, 10));
        lblArchivo.setForeground(Color.DARK_GRAY);
        
        JLabel lblTrack = new JLabel("Track: " + p.getTrack(), SwingConstants.CENTER);
        lblTrack.setFont(new Font("SansSerif", Font.BOLD, 10)); 
        lblTrack.setForeground(new Color(0, 102, 204)); 

        panel.add(lblTitulo);
        panel.add(lblArchivo);
        panel.add(lblTrack);
        
        panel.setToolTipText("Archivo completo: " + p.getFileName());

        return panel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
