/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author verol
 */
import CoreV2.Archivo;
import CoreV2.FileSystem;
import CoreV2.Lista;
import javax.swing.table.DefaultTableModel;

public class PanelTAAForm extends javax.swing.JPanel {

    /** Creates new form PanelTAAForm */
    public PanelTAAForm() {
        initComponents();
    }

    // --- CÓDIGO PROPIO ---
    public void actualizarVista(FileSystem fs) {
        DefaultTableModel modelo = (DefaultTableModel) tablaTAA.getModel();
        modelo.setRowCount(0); // Limpiar tabla
        
        Lista<Archivo> archivos = fs.getTablaDeArchivos();
        
        for (int i = 0; i < archivos.size(); i++) {
            Archivo arch = archivos.get(i);
            
            int inicio = -1;
            if (arch.getBloquesAsignados().size() > 0) {
                 inicio = arch.getBloquesAsignados().get(0);
            }
            
            String processName = arch.getProcessName() != null ? arch.getProcessName() : "N/A";
            Object[] fila = {arch.getNombre(), inicio, arch.getTamano(), processName};
            modelo.addRow(fila);
        }
    }
    // --------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTAA = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaTAA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre Archivo", "Inicio", "Size", "Process"
            }
        ));
        jScrollPane1.setViewportView(tablaTAA);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 100));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTAA;
    // End of variables declaration//GEN-END:variables
}
