/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import CoreV2.Disk;
import CoreV2.FileSystem;
import CoreV2.OperatingSystem;
import CoreV2.Proceso;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author verol
 */
public class SimuladorGUIForm extends javax.swing.JFrame {

    // --- 1. VARIABLES DEL BACKEND (AÑADIR ESTO) ---
    private Disk disk;
    private FileSystem fileSystem;
    private OperatingSystem so; 
    private Timer timerActualizacion;

    /**
     * Constructor vacío para el diseñador visual (NetBeans lo usa)
     */
    public SimuladorGUIForm() {
        initComponents();
    }

    // --- 2. CONSTRUCTOR REAL (AÑADIR ESTO) ---
    // Este es el que llamarás desde el Main.java
    public SimuladorGUIForm(Disk disk, FileSystem fileSystem, OperatingSystem so) {
        this.disk = disk;
        this.fileSystem = fileSystem;
        this.so = so; 
        
        initComponents(); // Inicia lo visual
        
        configurarVentana(); // Configuración extra
        iniciarTimer();      // Arranca el refresco automático
    }
    
    // --- 3. MÉTODOS DE CONFIGURACIÓN (AÑADIR ESTO) ---
    private void configurarVentana() {
        this.setTitle("Simulador SO - Gestión de Archivos");
        this.setLocationRelativeTo(null); // Centrar en pantalla
        
        // Inicializar la cuadrícula del panel de disco
        if (miPanelDisco != null && disk != null) {
            miPanelDisco.inicializarCuadricula(disk.getTotalBloques());
        }
    }

    private void iniciarTimer() {
        // Refrescar cada 100ms
        timerActualizacion = new Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                refrescarInterfaz();
            }
        });
        timerActualizacion.start();
    }

    private void refrescarInterfaz() {
        // Actualizar Disco (ahora también necesita FileSystem para mostrar nombres de archivos)
        if (miPanelDisco != null && disk != null) {
            miPanelDisco.actualizarVista(this.disk, this.fileSystem);
        }
        
        // Actualizar Tabla FAT
        if (miPanelTAA != null && fileSystem != null) {
            miPanelTAA.actualizarVista(this.fileSystem);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCrearNombre = new javax.swing.JTextField();
        txtCrearTamano = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        panelIzq = new javax.swing.JPanel();
        miPanelTAA = new Interfaces.PanelTAAForm();
        miPanelDisco = new Interfaces.PanelDiscoForm();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel2.setText("Tamano");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));
        getContentPane().add(txtCrearNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 80, -1));

        txtCrearTamano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrearTamanoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCrearTamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 80, -1));

        btnCrear.setText("CREAR");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        panelIzq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelIzq.add(miPanelTAA, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 500, 310));

        getContentPane().add(panelIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 830, 670));
        getContentPane().add(miPanelDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 650, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Modifica este método que ya tienes (o crea uno nuevo para el botón Crear)
    // Si le das doble clic al botón CREAR en "Design", te llevará aquí.
    
    private void txtCrearTamanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrearTamanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrearTamanoActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
try {
            // Obtener datos
            String nombre = txtCrearNombre.getText(); 
            String tamanoStr = txtCrearTamano.getText(); 
            
            // Validaciones
            if (nombre.isEmpty() || tamanoStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor llene nombre y tamaño.");
                return;
            }
            
            int tamano = Integer.parseInt(tamanoStr);
            
            if (tamano <= 0) {
                JOptionPane.showMessageDialog(this, "El tamaño debe ser mayor a 0.");
                return;
            }

            // ¡Acción! Crear proceso en el SO
            if (so != null) {
                System.out.println("GUI: Creando proceso para archivo: " + nombre);
                // Llamamos al método del SO que crea procesos IO_BOUND
                so.crearProceso(Proceso.Tipo.IO_BOUND, 0, nombre, tamano);
            } else {
                System.out.println("GUI Error: No hay conexión con el SO");
            }
            
            // Limpiar campos
            txtCrearNombre.setText("");
            txtCrearTamano.setText("");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El tamaño debe ser un número entero.");
        }    }//GEN-LAST:event_btnCrearActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SimuladorGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SimuladorGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SimuladorGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SimuladorGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SimuladorGUIForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private Interfaces.PanelDiscoForm miPanelDisco;
    private Interfaces.PanelTAAForm miPanelTAA;
    private javax.swing.JPanel panelIzq;
    private javax.swing.JTextField txtCrearNombre;
    private javax.swing.JTextField txtCrearTamano;
    // End of variables declaration//GEN-END:variables
}
